version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: subs-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgadmin
      POSTGRES_DB: subsdb
    ports:
      - "5432:5432"
    volumes:
      - subs_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: subs-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  subs_data: